#! /usr/bin/env python
import getpass
from argparse import ArgumentParser
from fullhouse import FullHouseConnection
from utils import print_table

def main(args):
    db = FullHouseConnection(args.db_host, args.db_port, args.db_name)
    jobs = db.all_jobs()
    if jobs:
        labels = 'user name status ntasks last_task cmd'.split()

        matrix = [ [j.get(k, '') for k in labels] for j in jobs]
        print_table(matrix, header=labels)

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('-db_host', type=str, default='localhost')
    parser.add_argument('-db_port', type=int, default=27017)
    parser.add_argument('-db_name', type=str, default='fullhouse')

    # If submitting from here
    parser.add_argument('jobids', type=str, metavar="jobs", nargs='*')

    args = parser.parse_args()
    main(args)

