#! /usr/bin/env python
import getpass
from argparse import ArgumentParser
from fullhouse import FullHouseConnection

def main(args):
    db = FullHouseConnection(args.db_host, args.db_port, args.db_name)
    job = db.template_job()
    job["jobname"] = args.jobname
    job["cmd"] = ' '.join(args.script)
    job["user"] = args.username
    job["cpu"] = args.cpu
    job["ntasks"] = args.tasks
    jid = db.register_job(job)
    print 'submitted job', jid

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('-db_host', type=str, default='localhost')
    parser.add_argument('-db_port', type=int, default=27017)
    parser.add_argument('-db_name', type=str, default='fullhouse')

    # If submitting from here
    parser.add_argument('--cpu', default='1', type=int)
    parser.add_argument('-n', '--jobname', type=str, default='')
    parser.add_argument('-u', '--username', type=str, default=getpass.getuser())
    parser.add_argument('-t', '--tasks', type=int, default=1)
    parser.add_argument('script', type=str, metavar="bash script", nargs='+')

    args = parser.parse_args()
    main(args)

